name: direct_native_cli
description: CLI tool for Direct Native framework
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.4.0
  path: ^1.8.0
  yaml: ^3.1.0
  cli_util: ^0.3.0

executables:
  direct_native: direct_native